apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  labels:
   app: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
    - image: busybox
      name: busybox
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      persistentVolumeClaim:
        claimName: mealie-data
